### PR TITLE
Fix to Reflection

### PR DESCRIPTION
**Pull request by AzuStar**
Fix lets the creation of classes that can override UnitEntity's methods to perform own actions.
`public class UnitEntity{
public UnitEntity(unit u){// constructor logic}
public virtual float WeaponDamage(){
return 100;
}
}`
`public class Footman : UnitEntity{
public Footman(unit u) : base(u){ // other logic}
public WeaponDamage(){
return base.WeaponDamage() * 10; // when damage engine caches it, it really returns 1000
}
}`
Example, but damage comes from real weapon aka 8 for footman and 17 for rifleman, but there is a class Footman which overrides it *10 aka 80.
image

### CODE REVIEW

**Comment by Drake53** [comment]
Can you test if changing the code in the System.isArrayLike function, as done in the commit linked below, also fixes the issue you were having?
https://github.com/yanghuan/CSharp.lua/commit/12615fc10e388d3e97d56c64c089e0b14f38adf7

**Comment by AzuStar** [comment]
isArrayLike doesn't seem to be the problem, with the original the problem was at line 964.
If you were to create an instance with no params, it would do just that, but, pars a single param and it does nothing.
I removed sophisticated checks for namespaces because they were not relevant to the War3 scenario anyway. Since garbage collector in Wc3 is behaving on its own and cannot be affected (real System.Reflection (C# equivalent of C++) including instance create, destroy, malloc, free etc) there is no point to ever call System services not defined in the translator. Activator is defined for example, so it can be used to create an instance, System.new calls internal lua bind, which is obv not set, so most of the code that doesn't work should be just removed from the translator since there is pretty much always counterpart that does it in predefined lua-space.

**Comment by Drake53** [comment]
I tried reproducing the error, but the function findMatchCtor returns nil for me, because metadata is nil. As a result, in my tests it executes line 966 instead of 964 (without problems though).

Can you tell me what the values of i, metadata.methods, and cls.__ctor__ are? I think your error may be caused by a mismatch in metadata.methods (in findMatchCtor) and cls.__ctor__ (in System.new). From what I can tell, the returned value i from findMatchCtor assumes that all ctors are at the start of metadata.methods. But if this is not the case, it will return a value greater than 1, which causes line 964 to be executed instead of 966. Additionally, if there is only a single constructor, cls.__ctor should be a single function, but System.new assumes it's a table/array by calling cls.__ctor__[index].

From the looks of it this problem is not specific to warcraft III, but is an issue with the coresystem library. Therefore, if a proper solution (that is not deleting the entire block of code) can be found, it should also be merged to the main repository. But to find a proper solution, we must first find the cause.

**Comment by AzuStar** [comment]
Since War3Net 1.3.x it has been fixed

**Pull request closed without merging**
